In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
print(a)

[1 2 3]


In [6]:
type(a)

numpy.ndarray

In [7]:
a.shape

(3,)

In [9]:
# 2次元配列
b = np.array([[1,2,3],[4,5,6]])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.shape

(2, 3)

In [13]:
c1 = np.array([0,1,2,3,4,5])
c1

array([0, 1, 2, 3, 4, 5])

In [14]:
c2 = c1.reshape((2,3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [16]:
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

In [17]:
a.dtype

dtype('int64')

In [18]:
d = np.array([1,2],dtype=np.int16)
d

array([1, 2], dtype=int16)

In [19]:
d.dtype

dtype('int16')

In [20]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [21]:
a

array([1, 2, 3])

In [22]:
a[0]

1

In [23]:
a[1:]

array([2, 3])

In [24]:
a[-1]

3

In [25]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
b[0]

array([1, 2, 3])

In [27]:
b[1,0]

4

In [28]:
b[:,2]

array([3, 6])

In [29]:
b[1,:]

array([4, 5, 6])

In [30]:
b[0,1:]

array([2, 3])

In [31]:
b[:,[0,2]]

array([[1, 3],
       [4, 6]])

In [32]:
a

array([1, 2, 3])

In [33]:
a[2] = 4
a

array([1, 2, 4])

In [34]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
b[1,2] = 7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [36]:
b[:,2] = 8
b

array([[1, 2, 8],
       [4, 5, 8]])